---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app: java-micro-service
  name: java-micro-service
  namespace: development
resources:
  - deployment.yaml
#  - service.yaml