apiVersion: app/v1
kind: Deployment
metada:
  labels:
    app: micro-docker
  name: micro-docker
  namespace: test
spec:
  replicas: 1 #si fuera stateful solo puedo tener 1 replica
  selector:
    matchLabels:
      app: micro-docker
  template:
    metadata:
      labels:
        app: micro-docker
    spec:
      containers:
      - image: micro-docker:1.2
        name: micro1
        env:
          - name: TRM
            value: 5000
        ports:
        - containerPort: 9090
          protocol: TCP